### ISSUE TITLE
Leaderboard project Not Mobile Responsive

### ISSUE THREAD

**Issue by Titus-Kiplagat** [Pi1998/leaderBoard#2]
###### Issue:
The project currently lacks mobile responsiveness, which is a critical feature in today's digital landscape. With an increasing number of users accessing websites and applications on mobile devices, it's essential to ensure a seamless experience for them.

###### Expected Behavior:
When accessing the project on a mobile device, users should be able to navigate, interact, and consume content without any usability issues. The layout and design should adapt to different screen sizes, making it visually appealing and user-friendly on smartphones and tablets.

**Comment by Pi1998** [comment]
I'll address the mobile responsiveness issue later. Thanks for the feedback, Titus! 👍
